### ISSUE TITLE
Regarding Gym

### ISSUE THREAD

**Issue by jkterry1** [modanesh/anomalous_rl_envs#1]
Hey, a few things

1) The top of your readme says "⭐️ Approved by OpenAI Gym ⭐️". Your inclusion in the third party environments list does not mean that at all. Any third party Gym environment is listed there.
2) Would you be interested in creating a PR to Gym that ads these changes as arguments to the classic control environments for the community to review, and to allow for upstreaming your work?

**Comment by modanesh** [comment]
Hi,

Sorry for the late response. 

1. Uh ok. I'll remove that.
2. Of course. That sounds great. I'm gonna start working on it and will let you know.
